import os
import boto3
from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------
# Amazon SES Client
# --------------------------------------------------

ses = boto3.client(
    "ses",
    region_name="us-east-1"
)

SOURCE_EMAIL = os.getenv(
    "SES_SOURCE_EMAIL",
    "prashantsanjay16@gmail.com"
)


# --------------------------------------------------
# Send notification to Admin
# --------------------------------------------------

def send_admin_notification(inquiry):

    subject = f"New Inquiry Received: {inquiry.subject}"

    body = f"""
A new customer inquiry has been submitted.

==================================================

Name:
{inquiry.name}

Email:
{inquiry.email}

Subject:
{inquiry.subject}

==================================================

AI Analysis

Summary:
{inquiry.summary}

Category:
{inquiry.category}

Priority:
{inquiry.priority}

Department:
{inquiry.department}

==================================================

Customer Message

{inquiry.message}

==================================================

Generated by Custom Inquiry Manager
"""

    ses.send_email(
        Source=SOURCE_EMAIL,

        Destination={
            "ToAddresses": [
                SOURCE_EMAIL
            ]
        },

        Message={
            "Subject": {
                "Data": subject
            },

            "Body": {
                "Text": {
                    "Data": body
                }
            }
        }
    )


# --------------------------------------------------
# Send confirmation email to Customer
# --------------------------------------------------

def send_confirmation_email(inquiry):

    subject = "We've received your inquiry"

    body = f"""
Hello {inquiry.name},

Thank you for contacting Custom Inquiry Manager.

We have successfully received your inquiry.

--------------------------------------------------

Subject:
{inquiry.subject}

Category:
{inquiry.category}

Priority:
{inquiry.priority}

--------------------------------------------------

Our AI system has analyzed your request and routed it to the appropriate department.

Our team will review your inquiry shortly.

Thank you for your patience.

Regards,

Custom Inquiry Manager
"""

    ses.send_email(
        Source=SOURCE_EMAIL,

        Destination={
            "ToAddresses": [
                inquiry.email
            ]
        },

        Message={
            "Subject": {
                "Data": subject
            },

            "Body": {
                "Text": {
                    "Data": body
                }
            }
        }
    )


# --------------------------------------------------
# Notify customer when inquiry status changes
# --------------------------------------------------

def send_status_update_email(inquiry):

    subject = f"Inquiry Status Updated - {inquiry.subject}"

    body = f"""
Hello {inquiry.name},

Your inquiry status has been updated.

-----------------------------------------

Subject:
{inquiry.subject}

Current Status:
{inquiry.status}

Category:
{inquiry.category}

Priority:
{inquiry.priority}

-----------------------------------------

Thank you for using Custom Inquiry Manager.

Regards,

Custom Inquiry Manager
"""

    ses.send_email(
        Source=SOURCE_EMAIL,

        Destination={
            "ToAddresses": [
                inquiry.email
            ]
        },

        Message={
            "Subject": {
                "Data": subject
            },

            "Body": {
                "Text": {
                    "Data": body
                }
            }
        }
    )